/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DeploymentPlatform model module.
 * @module model/DeploymentPlatform
 * @version 1.0
 */
export class DeploymentPlatform {
  /**
   * Constructs a new <code>DeploymentPlatform</code>.
   * @alias module:model/DeploymentPlatform
   * @class
   * @param userId {String} 
   * @param url {String} 
   * @param username {String} 
   * @param token {String} 
   */
  constructor(userId, url, username, token) {
    this.userId = userId;
    this.url = url;
    this.username = username;
    this.token = token;
  }

  /**
   * Constructs a <code>DeploymentPlatform</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeploymentPlatform} obj Optional instance to populate.
   * @return {module:model/DeploymentPlatform} The populated <code>DeploymentPlatform</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeploymentPlatform();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
DeploymentPlatform.prototype.id = undefined;

/**
 * @member {String} userId
 */
DeploymentPlatform.prototype.userId = undefined;

/**
 * @member {String} url
 */
DeploymentPlatform.prototype.url = undefined;

/**
 * @member {String} username
 */
DeploymentPlatform.prototype.username = undefined;

/**
 * @member {String} token
 */
DeploymentPlatform.prototype.token = undefined;

