/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ErrorError} from './ErrorError';

/**
 * The Error model module.
 * @module model/Error
 * @version 1.0
 */
export class Error {
  /**
   * Constructs a new <code>Error</code>.
   * @alias module:model/Error
   * @class
   * @param status {String} 
   * @param error {module:model/ErrorError} 
   */
  constructor(status, error) {
    this.status = status;
    this.error = error;
  }

  /**
   * Constructs a <code>Error</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Error} obj Optional instance to populate.
   * @return {module:model/Error} The populated <code>Error</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Error();
      if (data.hasOwnProperty('_status'))
        obj.status = ApiClient.convertToType(data['_status'], 'String');
      if (data.hasOwnProperty('_error'))
        obj.error = ErrorError.constructFromObject(data['_error']);
    }
    return obj;
  }
}

/**
 * @member {String} status
 */
Error.prototype.status = undefined;

/**
 * @member {module:model/ErrorError} error
 */
Error.prototype.error = undefined;

