/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ServiceRegistry model module.
 * @module model/ServiceRegistry
 * @version 1.0
 */
export class ServiceRegistry {
  /**
   * Constructs a new <code>ServiceRegistry</code>.
   * @alias module:model/ServiceRegistry
   * @class
   * @param userId {String} 
   * @param type {module:model/ServiceRegistry.TypeEnum} 
   * @param url {String} 
   * @param username {String} 
   * @param token {String} 
   */
  constructor(userId, type, url, username, token) {
    this.userId = userId;
    this.type = type;
    this.url = url;
    this.username = username;
    this.token = token;
  }

  /**
   * Constructs a <code>ServiceRegistry</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServiceRegistry} obj Optional instance to populate.
   * @return {module:model/ServiceRegistry} The populated <code>ServiceRegistry</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServiceRegistry();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ServiceRegistry.prototype.id = undefined;

/**
 * @member {String} userId
 */
ServiceRegistry.prototype.userId = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
ServiceRegistry.TypeEnum = {
  /**
   * value: "github"
   * @const
   */
  github: "github",

  /**
   * value: "gitlab"
   * @const
   */
  gitlab: "gitlab",

  /**
   * value: "bitbucket"
   * @const
   */
  bitbucket: "bitbucket",

  /**
   * value: "programmableweb"
   * @const
   */
  programmableweb: "programmableweb",

  /**
   * value: "docker"
   * @const
   */
  docker: "docker",

  /**
   * value: "iot_catalogue"
   * @const
   */
  iotCatalogue: "iot_catalogue"
};
/**
 * @member {module:model/ServiceRegistry.TypeEnum} type
 */
ServiceRegistry.prototype.type = undefined;

/**
 * @member {String} url
 */
ServiceRegistry.prototype.url = undefined;

/**
 * @member {String} username
 */
ServiceRegistry.prototype.username = undefined;

/**
 * @member {String} token
 */
ServiceRegistry.prototype.token = undefined;

