/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Team model module.
 * @module model/Team
 * @version 1.0
 */
export class Team {
  /**
   * Constructs a new <code>Team</code>.
   * @alias module:model/Team
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Team</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Team} obj Optional instance to populate.
   * @return {module:model/Team} The populated <code>Team</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Team();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('workflows'))
        obj.workflows = ApiClient.convertToType(data['workflows'], ['String']);
      if (data.hasOwnProperty('services'))
        obj.services = ApiClient.convertToType(data['services'], ['String']);
      if (data.hasOwnProperty('deployments'))
        obj.deployments = ApiClient.convertToType(data['deployments'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Team.prototype.id = undefined;

/**
 * @member {String} name
 */
Team.prototype.name = undefined;

/**
 * @member {Array.<String>} workflows
 */
Team.prototype.workflows = undefined;

/**
 * @member {Array.<String>} services
 */
Team.prototype.services = undefined;

/**
 * @member {Array.<String>} deployments
 */
Team.prototype.deployments = undefined;

