/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Workflow model module.
 * @module model/Workflow
 * @version 1.0
 */
export class Workflow {
  /**
   * Constructs a new <code>Workflow</code>.
   * @alias module:model/Workflow
   * @class
   * @param name {String} 
   * @param userId {String} 
   * @param gitCredentialsId {String} 
   * @param url {String} 
   * @param description {String} 
   * @param isPublic {Boolean} 
   * @param created {String} 
   * @param updated {String} 
   */
  constructor(name, userId, gitCredentialsId, url, description, isPublic, created, updated) {
    this.name = name;
    this.userId = userId;
    this.gitCredentialsId = gitCredentialsId;
    this.url = url;
    this.description = description;
    this.isPublic = isPublic;
    this.created = created;
    this.updated = updated;
  }

  /**
   * Constructs a <code>Workflow</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Workflow} obj Optional instance to populate.
   * @return {module:model/Workflow} The populated <code>Workflow</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Workflow();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('git_credentials_id'))
        obj.gitCredentialsId = ApiClient.convertToType(data['git_credentials_id'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('is_public'))
        obj.isPublic = ApiClient.convertToType(data['is_public'], 'Boolean');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'String');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Workflow.prototype.id = undefined;

/**
 * @member {String} name
 */
Workflow.prototype.name = undefined;

/**
 * @member {String} userId
 */
Workflow.prototype.userId = undefined;

/**
 * @member {String} gitCredentialsId
 */
Workflow.prototype.gitCredentialsId = undefined;

/**
 * @member {String} url
 */
Workflow.prototype.url = undefined;

/**
 * @member {String} description
 */
Workflow.prototype.description = undefined;

/**
 * @member {Boolean} isPublic
 */
Workflow.prototype.isPublic = undefined;

/**
 * @member {String} created
 */
Workflow.prototype.created = undefined;

/**
 * @member {String} updated
 */
Workflow.prototype.updated = undefined;

