/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {GitCredentials} from '../model/GitCredentials';

/**
* GitCredentials service.
* @module api/GitCredentialsApi
* @version 1.0
*/
export class GitCredentialsApi {

    /**
    * Constructs a new GitCredentialsApi. 
    * @alias module:api/GitCredentialsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the deleteGitCredentialsItem operation.
     * @callback moduleapi/GitCredentialsApi~deleteGitCredentialsItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes an GitCredentials document
     * @param {String} gitCredentialsId 
     * @param {module:api/GitCredentialsApi~deleteGitCredentialsItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteGitCredentialsItem(gitCredentialsId, callback) {
      
      let postBody = null;
      // verify the required parameter 'gitCredentialsId' is set
      if (gitCredentialsId === undefined || gitCredentialsId === null) {
        throw new Error("Missing the required parameter 'gitCredentialsId' when calling deleteGitCredentialsItem");
      }

      let pathParams = {
        'gitCredentialsId': gitCredentialsId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/git_credentials/{gitCredentialsId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getGitCredentials operation.
     * @callback moduleapi/GitCredentialsApi~getGitCredentialsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/GitCredentials>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves one or more GitCredentials documents
     * @param {module:api/GitCredentialsApi~getGitCredentialsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getGitCredentials(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [GitCredentials];

      return this.apiClient.callApi(
        '/git_credentials', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getGitCredentialsItem operation.
     * @callback moduleapi/GitCredentialsApi~getGitCredentialsItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GitCredentials{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves a GitCredentials document
     * @param {String} gitCredentialsId 
     * @param {module:api/GitCredentialsApi~getGitCredentialsItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getGitCredentialsItem(gitCredentialsId, callback) {
      
      let postBody = null;
      // verify the required parameter 'gitCredentialsId' is set
      if (gitCredentialsId === undefined || gitCredentialsId === null) {
        throw new Error("Missing the required parameter 'gitCredentialsId' when calling getGitCredentialsItem");
      }

      let pathParams = {
        'gitCredentialsId': gitCredentialsId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GitCredentials;

      return this.apiClient.callApi(
        '/git_credentials/{gitCredentialsId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the patchGitCredentialsItem operation.
     * @callback moduleapi/GitCredentialsApi~patchGitCredentialsItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a GitCredentials document
     * @param {module:model/GitCredentials} body A GitCredentials or list of GitCredentials documents
     * @param {String} gitCredentialsId 
     * @param {module:api/GitCredentialsApi~patchGitCredentialsItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    patchGitCredentialsItem(body, gitCredentialsId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling patchGitCredentialsItem");
      }
      // verify the required parameter 'gitCredentialsId' is set
      if (gitCredentialsId === undefined || gitCredentialsId === null) {
        throw new Error("Missing the required parameter 'gitCredentialsId' when calling patchGitCredentialsItem");
      }

      let pathParams = {
        'gitCredentialsId': gitCredentialsId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/git_credentials/{gitCredentialsId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the postGitCredentials operation.
     * @callback moduleapi/GitCredentialsApi~postGitCredentialsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates one or more GitCredentials documents
     * @param {module:model/GitCredentials} body A GitCredentials or list of GitCredentials documents
     * @param {module:api/GitCredentialsApi~postGitCredentialsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postGitCredentials(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling postGitCredentials");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/git_credentials', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}