/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {ServiceRegistry} from '../model/ServiceRegistry';

/**
* ServiceRegistry service.
* @module api/ServiceRegistryApi
* @version 1.0
*/
export class ServiceRegistryApi {

    /**
    * Constructs a new ServiceRegistryApi. 
    * @alias module:api/ServiceRegistryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the deleteServiceRegistryItem operation.
     * @callback moduleapi/ServiceRegistryApi~deleteServiceRegistryItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes an ServiceRegistry document
     * @param {String} serviceRegistryId 
     * @param {module:api/ServiceRegistryApi~deleteServiceRegistryItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteServiceRegistryItem(serviceRegistryId, callback) {
      
      let postBody = null;
      // verify the required parameter 'serviceRegistryId' is set
      if (serviceRegistryId === undefined || serviceRegistryId === null) {
        throw new Error("Missing the required parameter 'serviceRegistryId' when calling deleteServiceRegistryItem");
      }

      let pathParams = {
        'serviceRegistryId': serviceRegistryId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/service_registries/{serviceRegistryId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getServiceRegistries operation.
     * @callback moduleapi/ServiceRegistryApi~getServiceRegistriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ServiceRegistry>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves one or more ServiceRegistry documents
     * @param {module:api/ServiceRegistryApi~getServiceRegistriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getServiceRegistries(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ServiceRegistry];

      return this.apiClient.callApi(
        '/service_registries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getServiceRegistry operation.
     * @callback moduleapi/ServiceRegistryApi~getServiceRegistryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ServiceRegistry{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves a ServiceRegistry document
     * @param {String} serviceRegistryId 
     * @param {module:api/ServiceRegistryApi~getServiceRegistryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getServiceRegistry(serviceRegistryId, callback) {
      
      let postBody = null;
      // verify the required parameter 'serviceRegistryId' is set
      if (serviceRegistryId === undefined || serviceRegistryId === null) {
        throw new Error("Missing the required parameter 'serviceRegistryId' when calling getServiceRegistry");
      }

      let pathParams = {
        'serviceRegistryId': serviceRegistryId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ServiceRegistry;

      return this.apiClient.callApi(
        '/service_registries/{serviceRegistryId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the patchServiceRegistryItem operation.
     * @callback moduleapi/ServiceRegistryApi~patchServiceRegistryItemCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Updates a ServiceRegistry document
     * @param {module:model/ServiceRegistry} body A ServiceRegistry or list of ServiceRegistry documents
     * @param {String} serviceRegistryId 
     * @param {module:api/ServiceRegistryApi~patchServiceRegistryItemCallback} callback The callback function, accepting three arguments: error, data, response
     */
    patchServiceRegistryItem(body, serviceRegistryId, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling patchServiceRegistryItem");
      }
      // verify the required parameter 'serviceRegistryId' is set
      if (serviceRegistryId === undefined || serviceRegistryId === null) {
        throw new Error("Missing the required parameter 'serviceRegistryId' when calling patchServiceRegistryItem");
      }

      let pathParams = {
        'serviceRegistryId': serviceRegistryId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/service_registries/{serviceRegistryId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the postServiceRegistries operation.
     * @callback moduleapi/ServiceRegistryApi~postServiceRegistriesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Creates one or more ServiceRegistry documents
     * @param {module:model/ServiceRegistry} body A ServiceRegistry or list of ServiceRegistry documents
     * @param {module:api/ServiceRegistryApi~postServiceRegistriesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    postServiceRegistries(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling postServiceRegistries");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/service_registries', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}