/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmartClideDbApi);
  }
}(this, function(expect, SmartClideDbApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmartClideDbApi.CiManagerApi();
  });

  describe('(package)', function() {
    describe('CiManagerApi', function() {
      describe('deleteCiManagerItem', function() {
        it('should call deleteCiManagerItem successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteCiManagerItem call
          /*

          instance.deleteCiManagerItem(ciManagerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCiManagerItem', function() {
        it('should call getCiManagerItem successfully', function(done) {
          // TODO: uncomment, update parameter values for getCiManagerItem call and complete the assertions
          /*

          instance.getCiManagerItem(ciManagerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SmartClideDbApi.CiManager);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getCiManagers', function() {
        it('should call getCiManagers successfully', function(done) {
          // TODO: uncomment getCiManagers call and complete the assertions
          /*

          instance.getCiManagers(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SmartClideDbApi.CiManager);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchCiManagerItem', function() {
        it('should call patchCiManagerItem successfully', function(done) {
          // TODO: uncomment, update parameter values for patchCiManagerItem call
          /*

          instance.patchCiManagerItem(body, ciManagerId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postCiManagers', function() {
        it('should call postCiManagers successfully', function(done) {
          // TODO: uncomment, update parameter values for postCiManagers call
          /*

          instance.postCiManagers(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
