/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmartClideDbApi);
  }
}(this, function(expect, SmartClideDbApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmartClideDbApi.DeploymentPlatformApi();
  });

  describe('(package)', function() {
    describe('DeploymentPlatformApi', function() {
      describe('deleteDeploymentPlatformItem', function() {
        it('should call deleteDeploymentPlatformItem successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteDeploymentPlatformItem call
          /*

          instance.deleteDeploymentPlatformItem(deploymentPlatformId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDeploymentPlatform', function() {
        it('should call getDeploymentPlatform successfully', function(done) {
          // TODO: uncomment, update parameter values for getDeploymentPlatform call and complete the assertions
          /*

          instance.getDeploymentPlatform(deploymentPlatformId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SmartClideDbApi.DeploymentPlatform);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDeploymentPlatforms', function() {
        it('should call getDeploymentPlatforms successfully', function(done) {
          // TODO: uncomment getDeploymentPlatforms call and complete the assertions
          /*

          instance.getDeploymentPlatforms(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SmartClideDbApi.DeploymentPlatform);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchDeploymentPlatformItem', function() {
        it('should call patchDeploymentPlatformItem successfully', function(done) {
          // TODO: uncomment, update parameter values for patchDeploymentPlatformItem call
          /*

          instance.patchDeploymentPlatformItem(body, deploymentPlatformId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postDeploymentPlatforms', function() {
        it('should call postDeploymentPlatforms successfully', function(done) {
          // TODO: uncomment, update parameter values for postDeploymentPlatforms call
          /*

          instance.postDeploymentPlatforms(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
