/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmartClideDbApi);
  }
}(this, function(expect, SmartClideDbApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmartClideDbApi.DeploymentApi();
  });

  describe('(package)', function() {
    describe('DeploymentApi', function() {
      describe('deleteDeploymentItem', function() {
        it('should call deleteDeploymentItem successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteDeploymentItem call
          /*

          instance.deleteDeploymentItem(deploymentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDeploymentItem', function() {
        it('should call getDeploymentItem successfully', function(done) {
          // TODO: uncomment, update parameter values for getDeploymentItem call and complete the assertions
          /*

          instance.getDeploymentItem(deploymentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SmartClideDbApi.Deployment);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDeployments', function() {
        it('should call getDeployments successfully', function(done) {
          // TODO: uncomment getDeployments call and complete the assertions
          /*

          instance.getDeployments(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SmartClideDbApi.Deployment);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchDeploymentItem', function() {
        it('should call patchDeploymentItem successfully', function(done) {
          // TODO: uncomment, update parameter values for patchDeploymentItem call
          /*

          instance.patchDeploymentItem(body, deploymentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postDeployments', function() {
        it('should call postDeployments successfully', function(done) {
          // TODO: uncomment, update parameter values for postDeployments call
          /*

          instance.postDeployments(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
