/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmartClideDbApi);
  }
}(this, function(expect, SmartClideDbApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmartClideDbApi.GitCredentialsApi();
  });

  describe('(package)', function() {
    describe('GitCredentialsApi', function() {
      describe('deleteGitCredentialsItem', function() {
        it('should call deleteGitCredentialsItem successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteGitCredentialsItem call
          /*

          instance.deleteGitCredentialsItem(gitCredentialsId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getGitCredentials', function() {
        it('should call getGitCredentials successfully', function(done) {
          // TODO: uncomment getGitCredentials call and complete the assertions
          /*

          instance.getGitCredentials(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SmartClideDbApi.GitCredentials);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getGitCredentialsItem', function() {
        it('should call getGitCredentialsItem successfully', function(done) {
          // TODO: uncomment, update parameter values for getGitCredentialsItem call and complete the assertions
          /*

          instance.getGitCredentialsItem(gitCredentialsId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SmartClideDbApi.GitCredentials);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchGitCredentialsItem', function() {
        it('should call patchGitCredentialsItem successfully', function(done) {
          // TODO: uncomment, update parameter values for patchGitCredentialsItem call
          /*

          instance.patchGitCredentialsItem(body, gitCredentialsId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postGitCredentials', function() {
        it('should call postGitCredentials successfully', function(done) {
          // TODO: uncomment, update parameter values for postGitCredentials call
          /*

          instance.postGitCredentials(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
