/*
 * SmartCLIDE DB API
 * An API for accessing the SmartCLIDE database. (A Keycloak token is required, Authorization Bearer Token, for accessing the API outside the AWS cluster)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmartClideDbApi);
  }
}(this, function(expect, SmartClideDbApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmartClideDbApi.ServiceRegistryApi();
  });

  describe('(package)', function() {
    describe('ServiceRegistryApi', function() {
      describe('deleteServiceRegistryItem', function() {
        it('should call deleteServiceRegistryItem successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteServiceRegistryItem call
          /*

          instance.deleteServiceRegistryItem(serviceRegistryId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getServiceRegistries', function() {
        it('should call getServiceRegistries successfully', function(done) {
          // TODO: uncomment getServiceRegistries call and complete the assertions
          /*

          instance.getServiceRegistries(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SmartClideDbApi.ServiceRegistry);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getServiceRegistry', function() {
        it('should call getServiceRegistry successfully', function(done) {
          // TODO: uncomment, update parameter values for getServiceRegistry call and complete the assertions
          /*

          instance.getServiceRegistry(serviceRegistryId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SmartClideDbApi.ServiceRegistry);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('patchServiceRegistryItem', function() {
        it('should call patchServiceRegistryItem successfully', function(done) {
          // TODO: uncomment, update parameter values for patchServiceRegistryItem call
          /*

          instance.patchServiceRegistryItem(body, serviceRegistryId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postServiceRegistries', function() {
        it('should call postServiceRegistries successfully', function(done) {
          // TODO: uncomment, update parameter values for postServiceRegistries call
          /*

          instance.postServiceRegistries(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
